### ISSUE TITLE
Avoid extra ->get() call in templates.

### ISSUE THREAD

**Issue by Beanow** [Tuxion/tuxion.framework#20]
In my `Endpoint` I output the following.

``` php
$this->output(wrap(array(
  'Project' => $Project,
  'PackageType' => $PackageType,
  'Packages' => $Packages
)));
```

This is so that the standard data is in the format I prefer. However each of the variables are either model instances or resultsets. Meaning that in my templates I have to use an extra `->get()`. Because they get stored in an `ObjectWrapper`.

For example:

``` html
<h1><?=$t->Project->get()->title?></h1>
```

Preferably in (at least) templates this extra operation should be left out.

**Comment by Avaq** [comment]
That's exactly the issue I addressed in [this Trello card](https://trello.com/card/make-the-node-templator-better/50c0dc0366fc4871700067f9/8). Well.. You know. Anyway, I'll work on it. :)

**Comment by bartwr** [comment]
Outdated issue => Closed
